# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [32]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
np.ar

3. Create a vector with values ranging from 10 to 49

In [3]:
x =np.arange(10,49)

4. Find the shape of previous array in question 3

In [12]:
x.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
type(x)

numpy.ndarray

6. Print the numpy version and the configuration


In [11]:
print(np.__version__)
print(np.version)

1.19.3
<module 'numpy.version' from 'D:\\anaconda_setup\\lib\\site-packages\\numpy\\version.py'>


7. Print the dimension of the array in question 3


In [13]:
x.ndim

1

8. Create a boolean array with all the True values

In [15]:
np.arange(1,True)

array([], dtype=int32)

9. Create a two dimensional array




In [17]:
c = np.array([[1,2,3,4], [1,2,3,4]])
c

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

10. Create a three dimensional array



In [18]:
np.array([[['hello '] , ['world'] , ['new_world_order']]])

array([[['hello '],
        ['world'],
        ['new_world_order']]], dtype='<U15')

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [22]:
b = np.arange(1,16)
print(b)
print(b[::-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [31]:
z = np.zeros(10, dtype = int)
print(z)
print(z[6]== 1)

[0 0 0 0 0 0 0 0 0 0]
False


In [37]:
z[6] = 1
print(z)

[0 0 0 0 0 0 1 0 0 0]


13. Create a 3x3 identity matrix

In [54]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [51]:
e

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [56]:
arr = np.array([1,2,3,4,5], dtype = float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [57]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

In [58]:
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [60]:
arr1 == arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [62]:
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

18. Replace all odd numbers to -1 from previous array

In [9]:
fd =  np.arange(0,9,2)
fd



array([0, 2, 4, 6, 8])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [5]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [38]:
gf = np.array([[1,1,1,1,1],
          [1,1,1,1,1],
          [1,1,1,1,1],
          [1,1,1,1,1],
          [1,1,1,1,1]])
gf

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
gf[1:-1, 1:-1] = 0
gf

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [7]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1][1] = 12

print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [9]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [19]:
arr3d[0][0:] = 69
print(arr3d)

[[[69 69 69]
  [69 69 69]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [27]:
two = np.array([[1,2,3] , [4, 5, 6] , [5,8,5]])

In [28]:
two[0][0:]

array([1, 2, 3])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [29]:
two = np.array([[1,2,3] , [4, 5, 6] , [5,8,5]])

In [35]:
two[1][1]

5

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [39]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [5, 4, 3, 2]])

In [45]:
print(a[0][2:3])
print(a[1][2:3])

[3]
[7]


In [40]:
w = np.array([[0, 1, 2, 3, 4], [4, 5, 6, 7, 8]])

In [41]:
w

array([[0, 1, 2, 3, 4],
       [4, 5, 6, 7, 8]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [51]:
ca = np.arange(100).reshape(10,10)
print(f'this will show the max in above matrix {ca.max()}')

print(f'this will show the min in above matrix {ca.min()}')

this will show the max in above matrix 99
this will show the min in above matrix 0


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [53]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [54]:
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [56]:
np.searchsorted(a, b)

array([10,  1, 10,  1, 10,  5, 10,  5, 10, 10], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [63]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data
    ###################################

array([[-2.26995744,  0.94132019, -0.80168981,  1.20044328],
       [ 0.1739274 , -0.56879927, -0.66791391, -0.71277298],
       [-0.13920038, -1.09233763, -0.08137206,  0.42731126],
       [-0.99623175,  0.75884777,  0.90566765,  0.01553261],
       [ 0.79637933,  0.17249056, -1.35289241,  0.91629953],
       [ 0.56345192, -0.74208086, -0.32297109, -1.83636157],
       [ 0.42620549, -0.76003963, -0.09091684, -0.60887961]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

In [19]:
print(data[names != 'Joe'])
print(data[names != 'Will'])

[[-4.25388710e-01 -7.71004090e-01 -2.30907408e-01 -1.57639258e-01]
 [-1.06981240e+00 -8.02362970e-01 -3.44046857e-01 -3.46271814e-01]
 [-4.23794149e-01 -1.99988067e-01 -8.81536678e-04 -7.49021847e-01]
 [-9.57368047e-01  1.16398485e+00 -1.68879896e-01  5.24972357e-01]]
[[-4.25388710e-01 -7.71004090e-01 -2.30907408e-01 -1.57639258e-01]
 [-8.20526760e-02  8.47687474e-01  3.25912105e-01 -1.20860490e+00]
 [-4.23794149e-01 -1.99988067e-01 -8.81536678e-04 -7.49021847e-01]
 [ 8.30770283e-01 -1.33089798e+00  3.44672376e-01 -1.20792379e+00]
 [-2.18336389e-01 -3.73407927e-01  2.44086243e-01 -9.24273114e-01]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [71]:
xc = np.arange(1,16 , dtype=float ).reshape(5,3)

In [72]:
xc

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [77]:
zx = np.arange(1,17).reshape(2,2,4)
print(zx)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


33. Swap axes of the array you created in Question 32

In [89]:
zx.swapaxes(2,1)

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [20]:
ans = np.arange(10)
d = np.sqrt(ans)                                  #################

In [26]:
np.where(d <0.5, 0,ans )


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two 1


In [31]:
e = np.arange(12)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [22]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [26]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [33]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
print(a, b)

[1 2 3 4 5] [5 6 7 8 9]


In [34]:
del(b)

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [115]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray


array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [106]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [110]:
we = np.arange(20)
we

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [112]:
we.cumsum(axis = 0)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190], dtype=int32)