# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
import numpy as np

In [15]:
np.array([(0,1,2,3,4) , (5,6,7,8,9)] )

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [13]:
np.array([[(0,1,2,3,4), (5,6,7,8,9), (1,1,1,1,1),(1,1,1,1,1) ]])

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

### How to stack two arrays horizontally?

#### Desired Output::

In [17]:
np.array([(0, 1, 2, 3, 4, 1, 1, 1, 1, 1) , (5, 6, 7, 8, 9, 1, 1, 1, 1, 1)])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [22]:
y = np.array([(0, 1, 2, 3), (4, 5, 6, 7)])
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
y.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [26]:
cvx = np.array([[1,2,3,4], [2,3,4,5], [3,4,5,6]])

In [27]:
cvx.flatten()

array([1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [41]:
ty = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ty

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
df = ty.reshape(4,3)
df

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [48]:
wer = np.arange(25).reshape(5,5)


In [49]:
np.sqrt(wer)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

## Question:8

### Create 5x6 an array and find the mean?

In [52]:
wed = np.arange(30).reshape(5,6)
np.mean(wed)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [53]:
np.std(wed)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [54]:
np.median(wed)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [55]:
np.transpose(wed)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [62]:
f = np.arange(16).reshape(4,4)
gf = np.diagonal(f)
gf = sum(gf)
gf

30

## Question:13

### Find the determinant of the previous array in Q12?

In [67]:
a = np.array([[1,2], [3,4]]) 
np.linalg.det(a)

-2.0000000000000004

## Question:14

### Find the 5th and 95th percentile of an array?

In [78]:
tr = np.arange(100)
fifth = tr[5] 
nin = tr[95]


In [83]:
np.percentile(fifth, nin)

5.0

## Question:15

### How to find if a given array has any null values?

In [88]:
i = np.array([[(1,2,3,4), (5,6,7,np.nan)]])

In [89]:
np.isnan(i)

array([[[False, False, False, False],
        [False, False, False,  True]]])